/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */
import {
  rest
} from 'msw'
import faker from 'faker'

export const getGetOffersBySearchIdMock = () => ([...Array(faker.datatype.number({min: 1, max: 10}))].map(() => ({description: faker.random.word(), id: faker.random.word(), link: faker.random.word(), searchId: faker.random.word(), title: faker.random.word(), userId: faker.random.word()})))

export const getAddOfferMock = () => ({description: faker.random.word(), id: faker.random.word(), link: faker.random.word(), searchId: faker.random.word(), title: faker.random.word(), userId: faker.random.word()})

export const getGetOfferByIdMock = () => ({description: faker.random.word(), id: faker.random.word(), link: faker.random.word(), searchId: faker.random.word(), title: faker.random.word(), userId: faker.random.word()})

export const getModifyOfferMock = () => ({description: faker.random.word(), id: faker.random.word(), link: faker.random.word(), searchId: faker.random.word(), title: faker.random.word(), userId: faker.random.word()})

export const getDeleteOfferMock = () => (faker.datatype.boolean())

export const getOffersMSW = () => [
rest.get('*/searches/:searchId/offers', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetOffersBySearchIdMock()),
        )
      }),rest.post('*/searches/:searchId/offers', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getAddOfferMock()),
        )
      }),rest.get('*/searches/:searchId/offers/:offerId', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetOfferByIdMock()),
        )
      }),rest.put('*/searches/:searchId/offers/:offerId', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getModifyOfferMock()),
        )
      }),rest.delete('*/searches/:searchId/offers/:offerId', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getDeleteOfferMock()),
        )
      }),]
