/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */
import {
  rest
} from 'msw'
import faker from 'faker'

export const getGetPostByIdMock = () => ({UpdatedAt: faker.random.word(), companyAddress: faker.random.word(), companyEmail: faker.random.word(), companyName: faker.random.word(), companyPhoneNumber: faker.datatype.number(), companyUrl: faker.random.word(), contactEmail: faker.random.word(), contactFirstName: faker.random.word(), contactLastName: faker.random.word(), contactPhoneNumber: faker.datatype.number(), description: faker.random.word(), id: faker.random.word(), searchId: faker.random.word(), tags: [...Array(faker.datatype.number({min: 1, max: 10}))].map(() => (faker.random.word())), title: faker.random.word(), type: faker.random.word(), url: faker.random.word(), userEmail: faker.random.word(), userFirstName: faker.random.word(), userId: faker.random.word(), userLastName: faker.random.word()})

export const getPostsMSW = () => [
rest.get('*/searches/:searchId/posts/:postId', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetPostByIdMock()),
        )
      }),]
