/**
 * Generated by orval v6.2.3 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * An user
 */
export interface ClientDTO {
  amount?: number;
  clientId?: number;
  date?: string;
  description?: string;
  /** The id */
  id?: number;
  /** The first name */
  number?: string;
  subTotal?: number;
  total?: number;
  type?: number;
  vat?: number;
}
