/**
 * Generated by orval v6.2.3 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * An user
 */
export interface ClientDTO {
  address?: string;
  /** The e-mail */
  email?: string;
  /** The id */
  id?: number;
  /** The name */
  name?: string;
  organisationdid?: number;
  vatIncluded?: boolean;
  vatNumber?: string;
}
