/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * A comment
 */
export interface CommentUpdateDto {
  /** The content */
  content?: string;
  /** The id */
  id?: string;
  /** The post id */
  postId: string;
  /** The search id */
  searchId: string;
  /** UserId */
  userId: string;
}
