/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * An company
 */
export interface CompanyDTO {
  /** The description */
  description?: string;
  /** The id */
  id?: string;
  /** The link */
  link?: string;
  /** The SearchID */
  searchId?: string;
  /** The title */
  title?: string;
  /** The UserID */
  userId?: string;
}
