/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * A follower
 */
export interface FollowerDTO {
  /** The id */
  id?: string;
  /** The searchId */
  searchId?: string;
  /** The userId */
  userId?: string;
}
