/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * An friendship
 */
export interface FriendshipDTO {
  /** The id */
  id?: string;
  /** The searchId */
  searchId?: string;
  /** The state */
  state?: number;
  /** The type */
  type?: string;
  /** The userId */
  userId?: string;
}
