/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * A friend search
 */
export interface FriendSearchDTO {
  /** The description */
  description: string;
  /** The email */
  email?: string;
  /** The externalId */
  externalId?: string;
  /** The firstName */
  firstName?: string;
  /** The id */
  id?: string;
  /** The lastName */
  lastName?: string;
  /** The title */
  title: string;
  /** UserId */
  userId?: string;
}
