/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

export type GetSearchRole200 = 'owner' | 'friend' | 'follower' | 'visitor';


export const GetSearchRole200 = {
  owner: 'owner' as GetSearchRole200,
  friend: 'friend' as GetSearchRole200,
  follower: 'follower' as GetSearchRole200,
  visitor: 'visitor' as GetSearchRole200,
};
