/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */
import type { UserDTO } from './userDTO';

/**
 * My search
 */
export interface MySearchDTO {
  /** The participants */
  Participants?: UserDTO[];
  /** The id */
  id?: string;
  /** The search tags */
  tags?: string[];
  /** The title */
  title: string;
}
