/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * An network
 */
export interface NetworkDTO {
  /** The description */
  description?: string;
  /** The email */
  email?: string;
  /** The firstName */
  firstName?: string;
  /** The id */
  id?: string;
  /** The lastName */
  lastName?: string;
  /** The link */
  link?: string;
  /** The phoneNumber */
  phoneNumber?: string;
  /** The search id */
  searchId?: string;
  /** The user id */
  userId?: string;
}
