/**
 * Generated by orval v6.2.3 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * An network
 */
export interface NetworkDTO {
  /** The description */
  description?: string;
  /** The email */
  email?: string;
  /** The firstName */
  firstName: string;
  /** The id */
  id: number;
  /** The lastName */
  lastName: string;
  /** The link */
  link?: string;
  /** The phoneNumber */
  phoneNumber?: string;
  /** The search id */
  searchId: number;
  /** The user id */
  userId?: number;
}
