/**
 * Generated by orval v6.2.3 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * An offer
 */
export interface OfferDTO {
  /** The description */
  description?: string;
  /** The id */
  id?: number;
  /** The link */
  link?: string;
  /** the search id */
  searchId?: number;
  /** The title */
  title?: string;
  /** the user id */
  userId?: number;
}
