/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * An quest participant
 */
export interface ParticipantDTOForSearchById {
  /** Avatar url */
  avatarUrl?: string;
  /** The email */
  email?: string;
  /** The firstName */
  firstName?: string;
  /** The followerId */
  followerId?: string;
  /** The friendship id */
  friendshipId?: string;
  /** The id */
  id: string;
  /** The lastName */
  lastName?: string;
  /** The number of posts */
  numberOfPosts?: number;
  /** type */
  type?: string;
}
