/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */
import type { UserDTO } from './userDTO';
import type { SearchDTO } from './searchDTO';

/**
 * A Quest with owner and friends details
 */
export interface SearchWithOwnerAndFriendsDTO {
  /** Friends */
  friends?: UserDTO[];
  owner?: UserDTO;
  search?: SearchDTO;
}
