/**
 * Generated by orval v6.2.3 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */
import type { SearchDTO } from './searchDTO';

/**
 * search
 */
export type SearchDTOBody = SearchDTO;
