/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */

/**
 * An friendship
 */
export interface UpsertFriendshipRequestDTO {
  /** The state */
  state?: number;
  /** The type */
  type?: string;
}
