/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */
import {
  rest
} from 'msw'
import faker from 'faker'

export const getGetFriendshipsBySearchIdMock = () => ([...Array(faker.datatype.number({min: 1, max: 10}))].map(() => ({email: faker.random.word(), firstName: faker.random.word(), id: faker.random.word(), lastName: faker.random.word(), searchId: faker.random.word(), state: faker.datatype.number(), userId: faker.random.word()})))

export const getAddFriendshipMock = () => ({email: (() => faker.internet.email())(), firstName: (() => faker.name.firstName())(), id: faker.random.word(), lastName: (() => faker.name.lastName())(), searchId: faker.random.word(), state: faker.datatype.number(), userId: faker.random.word()})

export const getFriendshipsMSW = () => [
rest.get('*/searches/:searchId/friendships', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetFriendshipsBySearchIdMock()),
        )
      }),rest.post('*/searches/:searchId/friendships', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getAddFriendshipMock()),
        )
      }),]
