/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction
} from 'react-query'
import type {
  PostSearchResponseDTO,
  PostSearchRequestDTO,
  MySearchDTO,
  FollowedSearchDTO,
  SharedSearchDTO,
  SearchDTOById,
  SearchDTO,
  UserDTO,
  GetSearchFriendshipsParams,
  ParticipantDTOForSearchById,
  PostDTOBySearchId
} from '../../types/dtos'
import { customInstance } from '.././config'

type AsyncReturnType<
T extends (...args: any) => Promise<any>
> = T extends (...args: any) => Promise<infer R> ? R : any;


/**
 * type id struct
Create search.
Return search
 */
export const addSearch = (
    postSearchRequestDTO: PostSearchRequestDTO,
 ) => {
      return customInstance<PostSearchResponseDTO>(
      {url: `/searches`, method: 'post',
      data: postSearchRequestDTO
    },
      );
    }
  


    export const useAddSearch = <TError = void,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof addSearch>, TError,{data: PostSearchRequestDTO}, TContext>, }
) => {
      const {mutation: mutationOptions} = options || {}

      const mutationFn: MutationFunction<AsyncReturnType<typeof addSearch>, {data: PostSearchRequestDTO}> = (props) => {
          const {data} = props || {};

          return  addSearch(data,)
        }

      return useMutation<AsyncReturnType<typeof addSearch>, TError, {data: PostSearchRequestDTO}, TContext>(mutationFn, mutationOptions)
    }
    /**
 * Return my search
 * @summary Get my search.
 */
export const getMySearch = (
    
 ) => {
      return customInstance<MySearchDTO>(
      {url: `/searches/me`, method: 'get'
    },
      );
    }
  

export const getGetMySearchQueryKey = () => [`/searches/me`];

    
export const useGetMySearch = <TData = AsyncReturnType<typeof getMySearch>, TError = void>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getMySearch>, TError, TData>, }

  ) => {

  const {query: queryOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetMySearchQueryKey();
  const queryFn: QueryFunction<AsyncReturnType<typeof getMySearch>> = () => getMySearch();

  const query = useQuery<AsyncReturnType<typeof getMySearch>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}

/**
 * Return my followed searches
 * @summary Get my followed searches.
 */
export const getMyFollowedSearches = (
    
 ) => {
      return customInstance<FollowedSearchDTO[]>(
      {url: `/searches/public`, method: 'get'
    },
      );
    }
  

export const getGetMyFollowedSearchesQueryKey = () => [`/searches/public`];

    
export const useGetMyFollowedSearches = <TData = AsyncReturnType<typeof getMyFollowedSearches>, TError = void>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getMyFollowedSearches>, TError, TData>, }

  ) => {

  const {query: queryOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetMyFollowedSearchesQueryKey();
  const queryFn: QueryFunction<AsyncReturnType<typeof getMyFollowedSearches>> = () => getMyFollowedSearches();

  const query = useQuery<AsyncReturnType<typeof getMyFollowedSearches>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}

/**
 * Return my shared searches
 * @summary Get my shared searches.
 */
export const getMySharedSearches = (
    
 ) => {
      return customInstance<SharedSearchDTO[]>(
      {url: `/searches/shared`, method: 'get'
    },
      );
    }
  

export const getGetMySharedSearchesQueryKey = () => [`/searches/shared`];

    
export const useGetMySharedSearches = <TData = AsyncReturnType<typeof getMySharedSearches>, TError = void>(
  options?: { query?:UseQueryOptions<AsyncReturnType<typeof getMySharedSearches>, TError, TData>, }

  ) => {

  const {query: queryOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetMySharedSearchesQueryKey();
  const queryFn: QueryFunction<AsyncReturnType<typeof getMySharedSearches>> = () => getMySharedSearches();

  const query = useQuery<AsyncReturnType<typeof getMySharedSearches>, TError, TData>(queryKey, queryFn, queryOptions)

  return {
    queryKey,
    ...query
  }
}

/**
 * type id struct
Get search by id.
Return search
 */
export const getSearchById = (
    searchId: string,
 ) => {
      return customInstance<SearchDTOById>(
      {url: `/searches/${searchId}`, method: 'get'
    },
      );
    }
  

export const getGetSearchByIdQueryKey = (searchId: string,) => [`/searches/${searchId}`];

    
export const useGetSearchById = <TData = AsyncReturnType<typeof getSearchById>, TError = void>(
 searchId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getSearchById>, TError, TData>, }

  ) => {

  const {query: queryOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetSearchByIdQueryKey(searchId);
  const queryFn: QueryFunction<AsyncReturnType<typeof getSearchById>> = () => getSearchById(searchId, );

  const query = useQuery<AsyncReturnType<typeof getSearchById>, TError, TData>(queryKey, queryFn, {enabled: !!(searchId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}

/**
 * type id struct
Create search.
Return search
 */
export const modifySearch = (
    searchId: string,
    searchDTO: SearchDTO,
 ) => {
      return customInstance<SearchDTO>(
      {url: `/searches/${searchId}`, method: 'put',
      data: searchDTO
    },
      );
    }
  


    export const useModifySearch = <TError = void,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<AsyncReturnType<typeof modifySearch>, TError,{searchId: string;data: SearchDTO}, TContext>, }
) => {
      const {mutation: mutationOptions} = options || {}

      const mutationFn: MutationFunction<AsyncReturnType<typeof modifySearch>, {searchId: string;data: SearchDTO}> = (props) => {
          const {searchId,data} = props || {};

          return  modifySearch(searchId,data,)
        }

      return useMutation<AsyncReturnType<typeof modifySearch>, TError, {searchId: string;data: SearchDTO}, TContext>(mutationFn, mutationOptions)
    }
    /**
 * type id struct
Get friendships by search id.
Return users
 */
export const getSearchFriendships = (
    searchId: string,
    params?: GetSearchFriendshipsParams,
 ) => {
      return customInstance<UserDTO>(
      {url: `/searches/${searchId}/friendships`, method: 'get',
        params,
    },
      );
    }
  

export const getGetSearchFriendshipsQueryKey = (searchId: string,
    params?: GetSearchFriendshipsParams,) => [`/searches/${searchId}/friendships`, ...(params ? [params]: [])];

    
export const useGetSearchFriendships = <TData = AsyncReturnType<typeof getSearchFriendships>, TError = void>(
 searchId: string,
    params?: GetSearchFriendshipsParams, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getSearchFriendships>, TError, TData>, }

  ) => {

  const {query: queryOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetSearchFriendshipsQueryKey(searchId,params);
  const queryFn: QueryFunction<AsyncReturnType<typeof getSearchFriendships>> = () => getSearchFriendships(searchId,params, );

  const query = useQuery<AsyncReturnType<typeof getSearchFriendships>, TError, TData>(queryKey, queryFn, {enabled: !!(searchId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}

/**
 * type id struct
Get participants by search id.
Return participants
 */
export const getSearchParticipants = (
    searchId: string,
 ) => {
      return customInstance<ParticipantDTOForSearchById[]>(
      {url: `/searches/${searchId}/participants`, method: 'get'
    },
      );
    }
  

export const getGetSearchParticipantsQueryKey = (searchId: string,) => [`/searches/${searchId}/participants`];

    
export const useGetSearchParticipants = <TData = AsyncReturnType<typeof getSearchParticipants>, TError = void>(
 searchId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getSearchParticipants>, TError, TData>, }

  ) => {

  const {query: queryOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetSearchParticipantsQueryKey(searchId);
  const queryFn: QueryFunction<AsyncReturnType<typeof getSearchParticipants>> = () => getSearchParticipants(searchId, );

  const query = useQuery<AsyncReturnType<typeof getSearchParticipants>, TError, TData>(queryKey, queryFn, {enabled: !!(searchId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}

/**
 * type id struct
Get posts by search id.
Return posts
 */
export const getSearchPosts = (
    searchId: string,
 ) => {
      return customInstance<PostDTOBySearchId[]>(
      {url: `/searches/${searchId}/posts`, method: 'get'
    },
      );
    }
  

export const getGetSearchPostsQueryKey = (searchId: string,) => [`/searches/${searchId}/posts`];

    
export const useGetSearchPosts = <TData = AsyncReturnType<typeof getSearchPosts>, TError = void>(
 searchId: string, options?: { query?:UseQueryOptions<AsyncReturnType<typeof getSearchPosts>, TError, TData>, }

  ) => {

  const {query: queryOptions} = options || {}

  const queryKey = queryOptions?.queryKey ?? getGetSearchPostsQueryKey(searchId);
  const queryFn: QueryFunction<AsyncReturnType<typeof getSearchPosts>> = () => getSearchPosts(searchId, );

  const query = useQuery<AsyncReturnType<typeof getSearchPosts>, TError, TData>(queryKey, queryFn, {enabled: !!(searchId), ...queryOptions})

  return {
    queryKey,
    ...query
  }
}

