/**
 * Generated by orval v6.2.4 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */
import {
  rest
} from 'msw'
import faker from 'faker'

export const getGetCommentsForPostMock = () => ([...Array(faker.datatype.number({min: 1, max: 10}))].map(() => ({content: faker.random.word(), firstName: faker.random.word(), id: faker.random.word(), lastName: faker.random.word(), postId: faker.random.word(), searchId: faker.random.word(), userId: faker.random.word()})))

export const getCreateCommentForPostMock = () => ({content: faker.random.word(), firstName: (() => faker.name.firstName())(), id: faker.random.word(), lastName: (() => faker.name.lastName())(), postId: faker.random.word(), searchId: faker.random.word(), userId: faker.random.word()})

export const getUpdateCommentByIdMock = () => ({content: faker.random.word(), id: faker.random.word(), postId: faker.random.word(), searchId: faker.random.word(), userId: faker.random.word()})

export const getDeteCommentByIdMock = () => (faker.datatype.boolean())

export const getCommentsMSW = () => [
rest.get('*/searches/:searchId/posts/:postId/comments', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetCommentsForPostMock()),
        )
      }),rest.post('*/searches/:searchId/posts/:postId/comments', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getCreateCommentForPostMock()),
        )
      }),rest.put('*/searches/:searchId/posts/:postId/comments/:commentId', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getUpdateCommentByIdMock()),
        )
      }),rest.delete('*/searches/:searchId/posts/:postId/comments/:commentId', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getDeteCommentByIdMock()),
        )
      }),]
