/**
 * Generated by orval v6.2.3 🍺
 * Do not edit manually.
 * Jobbi Back-end
 * Swagger for Jobbi Back-end

Schemes: [http, https]
 * OpenAPI spec version: 1.0.0
 */
import {
  rest
} from 'msw'
import faker from 'faker'

export const getGetCompaniesBySearchIdMock = () => ([...Array(faker.datatype.number({min: 1, max: 10}))].map(() => ({description: faker.random.word(), id: faker.datatype.number(), link: faker.random.word(), searchId: faker.datatype.number(), title: faker.random.word(), userId: faker.datatype.number()})))

export const getAddCompanyMock = () => ({description: faker.random.word(), id: faker.datatype.number(), link: faker.random.word(), searchId: faker.datatype.number(), title: faker.random.word(), userId: faker.datatype.number()})

export const getGetCompanyByIdMock = () => ({description: faker.random.word(), id: faker.datatype.number(), link: faker.random.word(), searchId: faker.datatype.number(), title: faker.random.word(), userId: faker.datatype.number()})

export const getModifyCompanyMock = () => ({description: faker.random.word(), id: faker.datatype.number(), link: faker.random.word(), searchId: faker.datatype.number(), title: faker.random.word(), userId: faker.datatype.number()})

export const getCompaniesMSW = () => [
rest.get('*/searches/:searchId/companies', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetCompaniesBySearchIdMock()),
        )
      }),rest.post('*/searches/:searchId/companies', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getAddCompanyMock()),
        )
      }),rest.get('*/searches/:searchId/companies/:companyId', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getGetCompanyByIdMock()),
        )
      }),rest.put('*/searches/:searchId/companies/:companyId', (req, res, ctx) => {
        return res(
          ctx.delay(1000),
          ctx.status(200, 'Mocked status'),
ctx.json(getModifyCompanyMock()),
        )
      }),]
